import { Inter } from 'next/font/google'
import './globals.css'
import { Footer, Navbar } from '@/components'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Flash Buy',
  description: 'Generated by create next app and sanity cms',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layout">
          <header>
            <Navbar />
          </header>
        </div>
        <main className='main-container'>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
