import { Toaster } from 'react-hot-toast'
import './globals.css'
import { Footer, Navbar } from '@/components'
import { StateContext } from '@/context/StateContext'



export const metadata = {
  title: 'Flash Buy',
  description: 'Generated by create next app and sanity cms',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateContext>
          <div className="layout">
            <header>
              <Navbar />
            </header>
          </div>
          <Toaster />
            <main className='main-container'>
              {children}
            </main>
          <footer>
            <Footer />
          </footer>
        </StateContext>
      </body>
    </html>
  )
}
